"""initial schema: users, panel specs, weather, predictions, logs

Revision ID: 7da6f84bf2e8
Revises: eff0571ee805
Create Date: 2026-08-27 09:37:56.939103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da6f84bf2e8'
down_revision: Union[str, Sequence[str], None] = 'eff0571ee805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actual_output_logs_user_id_log_date_key', 'actual_output_logs', type_='unique')
    op.drop_index('idx_actual_output_logs_user_date', table_name='actual_output_logs')
    op.create_index(op.f('ix_actual_output_logs_user_id'), 'actual_output_logs', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_log_date', 'actual_output_logs', ['user_id', 'log_date'])
    op.drop_index('idx_panel_specs_user_id', table_name='panel_specs')
    op.create_index(op.f('ix_panel_specs_user_id'), 'panel_specs', ['user_id'], unique=False)
    op.drop_index('idx_predicted_output_user_time', table_name='predicted_output')
    op.create_index(op.f('ix_predicted_output_forecast_time'), 'predicted_output', ['forecast_time'], unique=False)
    op.create_index(op.f('ix_predicted_output_user_id'), 'predicted_output', ['user_id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('idx_weather_forecasts_location_time', table_name='weather_forecasts')
    op.create_index(op.f('ix_weather_forecasts_forecast_time'), 'weather_forecasts', ['forecast_time'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_latitude'), 'weather_forecasts', ['latitude'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_longitude'), 'weather_forecasts', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecasts_longitude'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_latitude'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_forecast_time'), table_name='weather_forecasts')
    op.create_index('idx_weather_forecasts_location_time', 'weather_forecasts', ['latitude', 'longitude', 'forecast_time'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_predicted_output_user_id'), table_name='predicted_output')
    op.drop_index(op.f('ix_predicted_output_forecast_time'), table_name='predicted_output')
    op.create_index('idx_predicted_output_user_time', 'predicted_output', ['user_id', 'forecast_time'], unique=False)
    op.drop_index(op.f('ix_panel_specs_user_id'), table_name='panel_specs')
    op.create_index('idx_panel_specs_user_id', 'panel_specs', ['user_id'], unique=False)
    op.drop_constraint('uq_user_log_date', 'actual_output_logs', type_='unique')
    op.drop_index(op.f('ix_actual_output_logs_user_id'), table_name='actual_output_logs')
    op.create_index('idx_actual_output_logs_user_date', 'actual_output_logs', ['user_id', 'log_date'], unique=False)
    op.create_unique_constraint('actual_output_logs_user_id_log_date_key', 'actual_output_logs', ['user_id', 'log_date'])
    # ### end Alembic commands ###
